### ISSUE TITLE
No reply playback Error.

### ISSUE THREAD

**Issue by yuchin067** [ConnectSDK/Connect-SDK-iOS#183]
I used playMediaWithMediaInfo method to play music and video. But it did't show any failure error about the format not support or the media file is break.
Is this normal right?

**Comment by eunikolsky** [comment]
@yuchin067, please provide some extra information — SDK version, what device you're connecting to and its version.

**Comment by yuchin067** [comment]
ConnectSDK version is 1.5.0
The firmware version Roku is 6.2.build3467, Chromecast 38401 and FireTV  51.1.6.3_user_516012020
Thanks.

**Comment by yuchin067** [comment]
Is no way to get error message if format not support or the media file is break?

**Comment by eunikolsky** [comment]
@yuchin067, playback on Roku was fixed in [1.6.0](https://github.com/ConnectSDK/Connect-SDK-iOS/tree/1.6.0).

**Comment by iadnan** [comment]
@yuchin067  Can you please verify if playback is working in ConnectSDK v1.6.0 . Thanks

**Comment by yuchin067** [comment]
I will try to use ConnectSDK v1.6.0. Once the results will reply to you.
Thanks.

**Comment by yuchin067** [comment]
I play break media file that still can't get any error message because success call back method will trigger, but it show the error message on FireTV

**Comment by iadnan** [comment]
@yuchin067 Can you provide the link to the media file you are trying to play.

**Comment by yuchin067** [comment]
Link: https://drive.google.com/file/d/0B-96ynJ1excZaDNsRjZJcEhqZE0
Thanks.

**Comment by iadnan** [comment]
Events support on Roku are not implemented yet, There is already an existing issue https://github.com/ConnectSDK/Connect-SDK-iOS/issues/167
